# Generated by Django 4.2.2 on 2023-06-20 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.product'),
        ),
        migrations.AddField(
            model_name='event',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.participant'),
        ),
    ]
