# Generated by Django 4.2.2 on 2023-06-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_tag_event_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='event.tag'),
        ),
    ]
