# Generated by Django 4.2.2 on 2023-06-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='review',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
